# Generated by Django 3.0.2 on 2020-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default=123, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
