# Generated by Django 3.0.2 on 2020-01-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='data_sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DataSheet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
